### ISSUE TITLE
Local Run keeps downloading dependency on Windows

### ISSUE THREAD

**Issue by SahilChoudhary22** [AutoFlowLabs/autoflow-studio-support#2]
## Issue Description
When running the app locally, dependencies keep forever downloading. 

## Environment
- Platform: Windows
- Screenshot: 
<img width="511" alt="Screenshot 2024-11-25 at 5 58 42 PM" src="https://github.com/user-attachments/assets/4dbee033-3884-4151-9882-12bc18bb701c">

## Expected Behavior
Dependencies should be downloaded quickly allowing user to run tests locally.

**Comment by brkerd** [comment]
On the developer console the following error is shown when trying to install dependencies:
`PWB Error executing command: Command failed: cd C:\Users\userName\AppData\Local\Programs\AutoFlow Studio\resources && node-win\npx node_modules/@playwright/test install `

The complete log is attached:
[2024-11-25T12_27_20_993Z-debug-0.log](https://github.com/user-attachments/files/17902964/2024-11-25T12_27_20_993Z-debug-0.log)

**Comment by SahilChoudhary22** [comment]
CC: @sertacdemirtas for visibility as he's also facing this issue

**Comment by SahilChoudhary22** [comment]
@brkerd @sertacdemirtas This has been fixed with v0.2.8. Feel free to re-open in case the issue is reproduced.

You'll get a notification to update when you open the app. OR you can download the latest installer through the same links here: https://autoflow.tools/downloads

**Comment by SahilChoudhary22** [comment]
**IMPORTANT NOTE:** If you've installed the app for all users on Windows. Run the app as administrator to install the dependencies required for local run. 

Platform: Windows
Version: v0.2.8
